### ISSUE TITLE
Use tensorflow 2.x can not load the offline model

### ISSUE THREAD

**Issue by iDustPan** [Helsinki-NLP/Tatoeba-Challenge#14]
Hello, 

I found your en-zh model on the Huggingface, I‘d liked to use it on a mobile device by Tensorflow Lite.  I need to covert the h5 model to a .tflite model to use it. 

When I tried to convert it, i found that i can not load the pre-trained model. 
Could you give any suggestions? Or could you offer a .pb model or a .tflite model directly?

My tensorflow version is 2.6.0.

this is my dir info:

```
(venv) ➜  Documents tree opus-mt-en-zh

opus-mt-en-zh
├── README.md
├── config.json
├── flax_model.msgpack
├── metadata.json
├── pytorch_model.bin
├── rust_model.ot
├── source.spm
├── target.spm
├── tf_model.h5
├── tokenizer_config.json
└── vocab.json
```

and failed with the code:

```
import tensorflow as tf
model = tf.keras.models.load_model("./opus-mt-en-zh",compile=False)


Traceback (most recent call last):
  File "translate.py", line 27, in <module>
    model = tf.keras.models.load_model("./opus-mt-en-zh",compile=False)
  File "/Users/xuanyue/venv/lib/python3.8/site-packages/keras/saving/save.py", line 205, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/Users/xuanyue/venv/lib/python3.8/site-packages/keras/saving/saved_model/load.py", line 108, in load
    meta_graph_def = tf.__internal__.saved_model.parse_saved_model(path).meta_graphs[0]
  File "/Users/xuanyue/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 118, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: ./opus-mt-en-zh/{saved_model.pbtxt|saved_model.pb}

```

**Comment by jorgtied** [comment]
I have no experience with this kind of conversion. Maybe people at huggingface can help you?
